# Generated by Django 4.1.7 on 2023-05-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userapikey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAPIKey',
            new_name='ChainVetAPIKey',
        ),
    ]
