# Generated by Django 4.1.7 on 2023-05-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_userapikey_chainvetapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_credits',
            field=models.IntegerField(default=0),
        ),
    ]
