# Generated by Django 4.1.7 on 2023-10-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_api_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='api_credits',
            new_name='credits_available',
        ),
        migrations.AddField(
            model_name='chainvetapikey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
