# Generated by Django 4.1.7 on 2023-10-22 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_accesscode_chainvetapikey_assigned_credits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('User', 'User'), ('AccessCode', 'AccessCode')], default='User', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_log', models.CharField(blank=True, max_length=32, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=128, null=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('access_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_logs', to='users.accesscode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
