# Generated by Django 4.1.7 on 2024-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_clientlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
