# Generated by Django 4.1.7 on 2024-01-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='affiliate_origin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.affiliate'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='affiliate_origin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.affiliate'),
        ),
    ]
