# Generated by Django 4.1.7 on 2024-01-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_accesscode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='affiliate_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.affiliate'),
        ),
    ]
