# Generated by Django 4.1.7 on 2024-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_accesscode_affiliate_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainvetapikey',
            name='reference',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
