# Generated by Django 4.1.7 on 2024-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_configvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='income_share',
            field=models.IntegerField(default=5000),
        ),
    ]
