# Generated by Django 4.1.7 on 2023-03-15 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPagePipelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('request_network', models.CharField(blank=True, max_length=64, null=True)),
                ('location_country', models.CharField(blank=True, max_length=128, null=True)),
                ('location_region', models.CharField(blank=True, max_length=128, null=True)),
                ('location_city', models.CharField(blank=True, max_length=128, null=True)),
                ('utc_offset', models.CharField(blank=True, max_length=128, null=True)),
                ('window_userAgent', models.CharField(blank=True, max_length=128, null=True)),
                ('window_inner_height', models.CharField(blank=True, max_length=128, null=True)),
                ('window_inner_width', models.CharField(blank=True, max_length=128, null=True)),
                ('log_type', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=128)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('request_parameters', models.JSONField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('request_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
