# Generated by Django 4.1.7 on 2024-04-01 09:24

import apps.corporate.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('partner', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=16)),
                ('payout_address', models.CharField(max_length=100)),
                ('tx_hash', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='corporate.account')),
            ],
            bases=(models.Model, apps.corporate.models.AmountMixin),
        ),
        migrations.CreateModel(
            name='AccountAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='corporate.account')),
            ],
            bases=(models.Model, apps.corporate.models.AmountMixin),
        ),
        migrations.CreateModel(
            name='AccountAdjustments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('account_to_adjust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='corporate.account')),
            ],
            bases=(models.Model, apps.corporate.models.AmountMixin),
        ),
    ]
