# Generated by Django 4.1.7 on 2023-05-24 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.IntegerField()),
                ('time_of_request', models.DateTimeField(auto_now_add=True)),
                ('type_of_assessment', models.CharField(choices=[('address', 'Address'), ('transaction', 'Transaction')], max_length=11)),
                ('response_data', models.JSONField()),
                ('status_assessment', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
