# Generated by Django 4.1.7 on 2023-05-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainvet', '0003_alter_assessment_status_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='address_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='risk_grade',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='risk_signals',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
