# Generated by Django 4.1.7 on 2023-10-27 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_clientlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chainvet', '0006_preorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='access_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='users.accesscode'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
