# Generated by Django 4.1.7 on 2024-01-18 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_affiliate'),
        ('chainvet', '0008_alter_order_total_price_usd_cents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pre_order',
        ),
        migrations.AddField(
            model_name='order',
            name='access_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_orders', to='users.accesscode'),
        ),
        migrations.AddField(
            model_name='order',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.affiliate'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=12345, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='owner_type',
            field=models.CharField(choices=[('User', 'User'), ('AccessCode', 'AccessCode')], default='User', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.DeleteModel(
            name='PreOrder',
        ),
    ]
