# Generated by Django 4.1.7 on 2024-01-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainvet', '0010_alter_assessment_assessment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anonpay_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
