# Generated by Django 4.1.7 on 2024-02-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainvet', '0012_order_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price_usd_cents',
            field=models.IntegerField(default=0),
        ),
    ]
