# Generated by Django 4.1.7 on 2024-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainvet', '0013_alter_order_total_price_usd_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='cbc_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
