# Generated by Django 4.1.7 on 2024-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainvet', '0017_assessment_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='network_populated_by_script',
            field=models.BooleanField(default=False),
        ),
    ]
