# Generated by Django 4.1.7 on 2024-04-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainvet', '0018_assessment_network_populated_by_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='accounting_crypto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='accounting_price_crypto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='accounting_price_usd_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
